export const ENGLISH_TOPICS = [
  // Verb Tenses
  "Simple Present",
  "Present Continuous",
  "Present Perfect",
  "Present Perfect Continuous",
  "Simple Past",
  "Past Continuous",
  "Past Perfect",
  "Past Perfect Continuous",
  "Simple Future (will)",
  "Future with Going To",
  "Future Continuous",
  "Future Perfect",

  // Grammar Structures
  "Modal Verbs (can, could, may, might, must, shall, should, will, would)",
  "Passive Voice",
  "Reported Speech",
  "Relative Clauses",
  "Conditionals (Zero & First)",
  "Conditionals (Second & Third)",
  "Gerunds and Infinitives",
  "Subject-Verb Agreement",
  "Comparatives and Superlatives",
  "Articles (a, an, the)",
  "Prepositions of Time and Place",
  "Conjunctions and Connectors",
  "Question Tags",
  "Causative Verbs",
  "Wish and If Only",
  "Used to / Would",
  "Phrasal Verbs",
  "Countable and Uncountable Nouns",
  "Quantifiers (some, any, much, many, few, little)",
  "Direct and Indirect Questions",

  // Vocabulary Themes
  "Vocabulary: Travel and Tourism",
  "Vocabulary: Food and Cooking",
  "Vocabulary: Health and Medicine",
  "Vocabulary: Technology and Innovation",
  "Vocabulary: Environment and Nature",
  "Vocabulary: Education and Learning",
  "Vocabulary: Work and Careers",
  "Vocabulary: Family and Relationships",
  "Vocabulary: Sports and Fitness",
  "Vocabulary: Art and Culture",
  "Vocabulary: Shopping and Money",
  "Vocabulary: Weather and Climate",
  "Vocabulary: City and Transportation",
  "Vocabulary: Emotions and Feelings",
  "Vocabulary: Crime and Justice",
  "Vocabulary: Media and Communication",
  "Vocabulary: Science and Research",
  "Vocabulary: Housing and Home",

  // Skills & Strategies
  "Reading Comprehension",
  "Listening Comprehension",
  "Idioms and Expressions",
  "Collocations",
  "Word Formation (prefixes, suffixes)",
  "Synonyms and Antonyms",
  "Formal vs Informal Register",
  "Academic Writing",
  "Essay Structure",
  "Paragraph Development",
  "Spelling Rules",
  "Punctuation",
];

export const TARGET_AUDIENCES = [
  { value: "high_school", label: "Estudiantes de colegio" },
  { value: "university", label: "Estudiantes universitarios" },
  { value: "independent", label: "Estudiantes independientes" },
];

export const SKILLS = [
  { value: "reading", label: "Reading", description: "Multiple choice questions based on reading passages" },
  { value: "writing", label: "Writing", description: "Write texts using evaluated topics, with grammar/spelling feedback" },
  { value: "listening", label: "Listening", description: "Listen to audio and answer multiple choice questions" },
  { value: "speaking", label: "Speaking", description: "Read a paragraph aloud and record your response" },
];
